### ISSUE TITLE
Deploy Deployment

### ISSUE THREAD

**Issue by gregtampa** [turtle0x1/LxdMosaic#258]
`Host: https://10.93.42.1:8443 Create LXC container: Invalid devices: Detect root disk device: No root device could be found /var/www/LxdMosaic/src/classes/Tools/Instances/CreateInstance.php 66`

Am i Missing how to create instances? I get this error

some more outputs from my console to show there is a root device:
```
azureuser@Neo-dev:~$ lxc profile show default
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/containers/lxdMosaic
azureuser@Neo-dev:~$ lxc profile device add default root disk path=/ pool=default
Error: The device already exists
azureuser@Neo-dev:~$ lxc storage list
+---------+-------------+--------+--------------------------------+---------+
|  NAME   | DESCRIPTION | DRIVER |             SOURCE             | USED BY |
+---------+-------------+--------+--------------------------------+---------+
| default |             | zfs    | /var/lib/lxd/disks/default.img | 3       |
+---------+-------------+--------+--------------------------------+---------+
azureuser@Neo-dev:~$ lxc ls
+-----------+---------+---------------------+----------------------------------------------+------------+-----------+
|   NAME    |  STATE  |        IPV4         |                     IPV6                     |    TYPE    | SNAPSHOTS |
+-----------+---------+---------------------+----------------------------------------------+------------+-----------+
| lxdMosaic | RUNNING | 10.93.42.234 (eth0) | fd42:11dd:87f1:fb9:216:3eff:fe7d:baad (eth0) | PERSISTENT | 0         |
+-----------+---------+---------------------+----------------------------------------------+------------+-----------+
azureuser@Neo-dev:~$lxc storage show default
config:
  size: 15GB
  source: /var/lib/lxd/disks/default.img
  zfs.pool_name: default
description: ""
name: default
driver: zfs
used_by:
- /1.0/containers/lxdMosaic
- /1.0/images/4746a4889a31e449e6c5e2764eb733a60e85131be3165c91d5f5a8346f0ba43c
- /1.0/profiles/default
status: Created
locations:
- none

```

perhaps cause im using zfs?

**Comment by gregtampa** [comment]
```
lxc storage show default
config:
  size: 15GB
  source: /var/lib/lxd/disks/default.img
  zfs.pool_name: default
description: ""
name: default
driver: zfs
used_by:
- /1.0/containers/lxdMosaic
- /1.0/images/4746a4889a31e449e6c5e2764eb733a60e85131be3165c91d5f5a8346f0ba43c
- /1.0/profiles/default
status: Created
locations:
- none

```

When trying to create project is in title of popup
however i clicked storage then the + sign on right to create a pool.
filled it in using driver BTRFS
