### ISSUE TITLE
Issues accesing LxdMosaic from two networks

### ISSUE THREAD

**Issue by dzidek23** [turtle0x1/LxdMosaic#278]
**Describe the bug**
I'm running Lxdmosaic from a snap on machine connected to two separate networks. Reaching the dashboard from one network works without a problem, the other shows the skeleton of the dash (with placeholders only). see screenshots...

**Screenshots**
![lxdmosaic2](https://user-images.githubusercontent.com/70292029/97995790-e3febd80-1dde-11eb-8470-7f9728b83cde.png)
![lxdmosaic](https://user-images.githubusercontent.com/70292029/97995792-e4975400-1dde-11eb-9d46-9f318699f5f6.png)

snap/lxdmosaic/33/apachelog/logs/php_errors.log:

[02-Nov-2020 14:10:44 UTC] PHP Warning:  filemtime(): stat failed for /snap/lxdmosaic/33/htdocs/src/classes/App/../../assets/jqueryConfirm/dist/jquery-confirm.min.js in /snap/lxdmosaic/33/htdocs/src/classes/App/
[02-Nov-2020 14:10:44 UTC] PHP Warning:  md5_file(/snap/lxdmosaic/33/htdocs/src/classes/App/../../assets/jqueryConfirm/dist/jquery-confirm.min.js): failed to open stream: No such file or directory in /snap/lxdmo
[02-Nov-2020 16:06:37 UTC] PHP Warning:  Invalid argument supplied for foreach() in /snap/lxdmosaic/33/htdocs/src/classes/Tools/Instances/Files/GetPath.php on line 60
[02-Nov-2020 16:06:37 UTC] PHP Warning:  Invalid argument supplied for foreach() in /snap/lxdmosaic/33/htdocs/src/classes/Tools/Instances/Files/GetPath.php on line 77

 - OS: Linux 5.4.0-52-generic #57-Ubuntu
 - Browser Firefox
 - Version 81.0.2

**Additional context**
```
netplan.conf
network:
  ethernets:
    enp5s0:
      dhcp4: no
      optional: true
    enp6s5:
      dhcp4: no
  bridges:
    br_ext:
        interfaces: [enp5s0]
        addresses: [xxx.xxx.1.104/24]
        gateway4: xxx.xxx.1.254
        mtu: 1500
        nameservers:
          addresses: [xxx.xxx..1.254]
        dhcp4: no
        dhcp6: true
    br_int:
        interfaces: [enp6s5]
        addresses: [xxx.xxx.162.50/23]
        routes:
        - to: xxx.xxx.0.0/16
          via: xxx.xxx.162.4
        mtu: 1500
        nameservers:
          addresses: [xxx.xxx.161.11]
        parameters:
           stp: true
           forward-delay: 4
        dhcp4: no
        dhcp6: true
  version: 2
```
