### ISSUE TITLE
Profile for lxd

### ISSUE THREAD

**Issue by sstubbs** [turtle0x1/LxdMosaic#428]
**Is your feature request related to a problem? Please describe.**
I see that using the snap is not recommended and so will use lxd container as suggested in the docs. Ideally I prefer to use lxd profiles for every container I have.

**Describe the solution you'd like**
A working lxd profile would be great. I've tried the following but it does not work
```
config:
  boot.autostart: "true"
  user.user-data: |
    #cloud-config
    runcmd:
    - 'curl https://raw.githubusercontent.com/turtle0x1/LxdMosaic/master/examples/install_with_clone.sh >> installLxdMosaic.sh'
    - 'chmod +x installLxdMosaic.sh'
    - './installLxdMosaic.sh'
```

**Describe alternatives you've considered**
I can create the container and use lxc shell manually but I would rather not.
