### ISSUE TITLE
images won't download

### ISSUE THREAD

**Issue by lhorace** [turtle0x1/LxdMosaic#49]
**Describe the bug**
Hey \o again,

I'm having trouble downloading images here and I wasn't able to determine the cause.

**To Reproduce**
1. Go to Images -> Linux Continaers Org
2. Try to import any image

**Expected behavior**
Image is importing on host

**Actual behavior**
Errors out

**Screenshots**
![Screenshot from 2019-03-31 15 36 24](https://user-images.githubusercontent.com/12678456/55294069-72bd8400-53cb-11e9-8d31-5cb8fcf1ead4.png)

**Comment by turtle0x1** [comment]
if the operation error is showing it means lxd isnt happy for some reason not LXDMosaic, ill take a look at showing the error message tommorow, but your investigations should be directed towards lxd

**Comment by lhorace** [comment]
```
linux-desktop :: /var/log/lxd # lxc image copy images:archlinux/current/amd64 local: --alias archlinux --auto-update                                                                                                                               
Image copied successfully!
```
Works fine from the machine itself and I didn't find anything relevant from lxd logs.

```
Mar 30 11:13:02 linux-desktop lxd[2060]: t=2019-03-30T11:13:02-0400 lvl=warn msg="Detected poll(POLLNVAL) event."
```

    but your investigations should be directed towards lxd

I couldn't tell if this was API issue or LXD itself, see above. I'll look into turning on debugging on LXD and see what it spits out.

**Comment by lhorace** [comment]
```
'Get https://images.linuxcontainers.org:8443/1.0: Unable to connect to: images.linuxcontainers.org:8443'
```
My suspicious is LXD is using the wrong interface to download the image, does this make sense to you? Why port 8443?

**Comment by turtle0x1** [comment]
do you get this problem on the alpine image ? i import that one all the time no problem

**Comment by lhorace** [comment]
It looks to me that port 8443 needed to open, which is odd. It appears that CLI has a completely different behaviour. I'll run some more tests.

**Comment by turtle0x1** [comment]
outbound 8443 ?

**Comment by lhorace** [comment]
Yup.

Full transaction:  

```
metadata:
  context: {}
  level: dbug
  message: 'New task operation: dd2050c9-9d68-4dd3-936d-0a2151de5ac0'
timestamp: "2019-03-31T16:54:49.139576853-04:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Started task operation: dd2050c9-9d68-4dd3-936d-0a2151de5ac0'
timestamp: "2019-03-31T16:54:49.139629902-04:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: Connecting to a remote public LXD over HTTPs
timestamp: "2019-03-31T16:54:49.13968223-04:00"
type: logging


metadata:
  class: task
  created_at: "2019-03-31T16:54:49.130687523-04:00"
  description: Downloading image
  err: ""
  id: dd2050c9-9d68-4dd3-936d-0a2151de5ac0
  may_cancel: false
  metadata: null
  resources: null
  status: Pending
  status_code: 105
  updated_at: "2019-03-31T16:54:49.130687523-04:00"
timestamp: "2019-03-31T16:54:49.139608632-04:00"
type: operation


metadata:
  class: task
  created_at: "2019-03-31T16:54:49.130687523-04:00"
  description: Downloading image
  err: ""
  id: dd2050c9-9d68-4dd3-936d-0a2151de5ac0
  may_cancel: false
  metadata: null
  resources: null
  status: Running
  status_code: 103
  updated_at: "2019-03-31T16:54:49.130687523-04:00"
timestamp: "2019-03-31T16:54:49.139637737-04:00"
type: operation


metadata:
  context:
    etag: ""
    method: GET
    url: https://images.linuxcontainers.org:8443/1.0
  level: dbug
  message: Sending request to LXD
timestamp: "2019-03-31T16:54:49.139726824-04:00"
type: logging


metadata:
  context:
    k: "1"
  level: dbug
  message: Found cert
timestamp: "2019-03-31T16:55:01.821562118-04:00"
type: logging


metadata:
  context:
    ip: 10.0.3.2:53610
    method: GET
    url: /1.0/resources
  level: dbug
  message: handling
timestamp: "2019-03-31T16:55:01.821591553-04:00"
type: logging


metadata:
  context:
    ip: 10.0.3.2:53610
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2019-03-31T16:55:01.83530583-04:00"
type: logging


metadata:
  context:
    k: "1"
  level: dbug
  message: Found cert
timestamp: "2019-03-31T16:55:01.835283348-04:00"
type: logging


metadata:
  context:
    k: "1"
  level: dbug
  message: Found cert
timestamp: "2019-03-31T16:55:01.835575897-04:00"
type: logging


metadata:
  context:
    k: "1"
  level: dbug
  message: Found cert
timestamp: "2019-03-31T16:55:01.880298482-04:00"
type: logging


metadata:
  context:
    ip: 10.0.3.2:53610
    method: GET
    url: /1.0/containers?project=default
  level: dbug
  message: handling
timestamp: "2019-03-31T16:55:01.880326836-04:00"
type: logging


metadata:
  context:
    ip: 10.0.3.2:53610
    method: GET
    url: /1.0/containers/lxdmosaic/state?project=default
  level: dbug
  message: handling
timestamp: "2019-03-31T16:55:01.881118089-04:00"
type: logging


metadata:
  context:
    k: "1"
  level: dbug
  message: Found cert
timestamp: "2019-03-31T16:55:01.881100106-04:00"
type: logging

```

**Comment by lhorace** [comment]
I have a Firewall between the machine and internet with only specifics ports opened, apparently (outbound)TCP port 8443 is required to be open to pull images.

```
metadata:
  context:
    etag: ""
    method: GET
    url: https://images.linuxcontainers.org:8443/1.0
  level: dbug
  message: Sending request to LXD
timestamp: "2019-03-31T16:54:49.139726824-04:00"
type: logging
```

**Comment by lhorace** [comment]
```
metadata:
  context: {}
  level: dbug
  message: 'New task operation: 523d5b60-6752-4e0d-9073-a0b6390383cd'
timestamp: "2019-03-31T17:08:56.55543576-04:00"
type: logging


metadata:
  class: task
  created_at: "2019-03-31T17:08:56.542647859-04:00"
  description: Downloading image
  err: ""
  id: 523d5b60-6752-4e0d-9073-a0b6390383cd
  may_cancel: false
  metadata: null
  resources: null
  status: Pending
  status_code: 105
  updated_at: "2019-03-31T17:08:56.542647859-04:00"
timestamp: "2019-03-31T17:08:56.555480884-04:00"
type: operation


metadata:
  context:
    expiry: 2019-03-31 18:01:58.098997528 -0400 EDT m=+122519.066008775
    server: https://images.linuxcontainers.org
  level: dbug
  message: Using SimpleStreams cache entry
timestamp: "2019-03-31T17:08:56.555627369-04:00"
type: logging
```

Not sure what API you are using to initiate the pull request, the request appears to go over port 443. Not sure if you want to look into this or not, at least I know the cause.

Cheers.
